name: ESLint, TS & Prettier Check
on:
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint:strict

  typecheck:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Type check
        run: yarn typecheck

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download deps
        uses: bahmutov/npm-install@v1

      - name: Type check
        run: yarn format:check
